<?xml version="1.0" encoding="utf-8"?><Database Name="analitica_pruebas" Class="ANALITICA_DataContexDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=138.121.200.242;Initial Catalog=analitica_pruebas;Persist Security Info=True;User ID=userappsami;Connect Timeout=120" SettingsObjectName="ANALITICA_COMMON.Properties.Settings" SettingsPropertyName="analitica_pruebasConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.rips_depurados_carguebase" Member="rips_depurados_carguebase">
    <Type Name="rips_depurados_carguebase">
      <Column Name="id_cargue_base" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="tipo_archivo_rips" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="id_mes" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_año" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="fecha_digita" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="usuario_digita" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.rips_depurados_ac_carguedtll" Member="rips_depurados_ac_carguedtll">
    <Type Name="rips_depurados_ac_carguedtll">
      <Column Name="id_cague_dtll" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_cargue_base" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="numero_de_la_factura" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="codigo_prestador_servicios_de_salud" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="tipo_identificacion_del_usuario" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="numero_identificacion_usuario" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="fecha_consulta" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="numero_de_autorizacion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="codigo_consulta" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="finalidad_consulta" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="causa_externa" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="codigo_diagnostico_principal" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="codigo_diagnostico_relacionado_no_1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="codigo_diagnostico_relacionado_no_2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="codigo_diagnostico_relacionado_no_3" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tipo_diagnostico_principal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="valor_consulta" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="valor_cuota_moderadora" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="valor_neto_a_pagar" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="prestador" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="descripcion_consulta" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="descripcion_finalidad_de_la_consulta" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="descripcion_causa_externa" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="descripcion_tipo_diagnostico_principal" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="descripcion_del_diagnostico_principal" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="descripcion_del_diagnostico_relacionado_no_1" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="descripcion_del_diagnostico_relacionado_no_2" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="descripcion_del_diagnostico_relacionado_no_3" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="grupo_dx" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="ciudad_prestador" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="regional_prestador" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="posible_duplicado" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.rips_depurados_au_carguedtll" Member="rips_depurados_au_carguedtll">
    <Type Name="rips_depurados_au_carguedtll">
      <Column Name="id_cague_dtll" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_cargue_base" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="numero_factura" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="codigo_prestador_servicios_de_salud" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="tipo_identificacion_usuario" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="numero_identificacion_usuario" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Fecha_ingreso_usuario_a_observacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="hora_de_ingreso_del_usuario_a_observacion" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="numero_de_autorizacion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="causa_externa" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="diagnostico_de_la_salida" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="diagnostico_relacionado_no_1_a_la_salida" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="diagnostico_relacionado_no_2_a_la_salida" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="diagnostico_relacionado_no_3_a_la_salida" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="destino_del_usuario_a_la_salida_de_observacion" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="estado_a_la_salida" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="causa_basica_de_muerte_en_urgencias" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="fecha_de_la_salida_del_usuario_en_observacion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="hora_de_la_salida_del_usuario_en_observacion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="prestador" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="descripcion_causa_externa" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="descripcion_destino_del_usuario_a_la_salida_de_observacion" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="descripcion_estado_a_la_salida" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="descripcion_diagnostico_de_salida" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="descripcion_diagnostico_relacionado_no_1_a_la_salida" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="descripcion_diagnostico_relacionado_no_2_a_la_salida" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="descripcion_diagnostico_relacionado_no_3_a_la_salida" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="descripcion_causa_basica_de_muerte_en_urgencias" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="grupo_dx" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="ciudad_prestador" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="regional_prestador" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="posible_duplicado" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.rips_depurados_ah_carguedtll" Member="rips_depurados_ah_carguedtll">
    <Type Name="rips_depurados_ah_carguedtll">
      <Column Name="id_cague_dtll" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_cargue_base" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="numero_de_la_factura" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="codigo_del_prestador_de_servicios_de_salud" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="tipo_de_documento_de_identificacion_del_usuario" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="numero_de_identificacion_del_usuario_en_el_sistema" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="via_de_ingreso_a_la_institucion" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="fecha_de_ingreso_del_usuario_a_la_institucion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="hora_de_ingreso_del_usuario_a_la_institucion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="numero_de_autorizacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="causa_externa" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="diagnostico_principal_de_ingreso" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="diagnostico_principal_de_egreso" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="diagnostico_relacionado_no_1_de_egreso" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="diagnostico_relacionado_no_2_de_egreso" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="diagnostico_relacionado_no_3_de_egreso" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="diagnostico_de_la_complicacion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="estado_a_la_salida" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="diagnostico_de_la_causa_basica_de_muerte" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="fecha_de_egreso_del_usuario_a_la_institucion" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="hora_de_egreso_del_usuario_de_la_institucion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="prestador" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="descripcion_via_de_ingreso_a_la_institucion" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="descripcion_causa_externa" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="descripcion_estado_de_la_salida" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="descripcion_diagnostico_principal_de_ingreso" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="descripcion_diagnostico_principal_de_egreso" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="descripcion_diagnostico_relacionado_no_1_de_egreso" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="descripcion_diagnostico_relacionado_no_2_de_egreso" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="descripcion_diagnostico_relacionado_no_3_de_egreso" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="descripcion_diagnostico_de_la_complicacion" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="descripcion_diagnostico_de_la_causa_basica_de_muerte" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="grupo_dx" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="ciudad_prestador" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="regional_prestador" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="posible_duplicado" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.rips_depurados_am_carguedtll" Member="rips_depurados_am_carguedtll">
    <Type Name="rips_depurados_am_carguedtll">
      <Column Name="id_cague_dtll" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_cargue_base" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="numero_de_la_factura" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="codigo_prestador_de_servicios_de_salud" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="tipo_identificacion_usuario" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="numero_identificacion_del_usuario_en_el_sistema" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="numero_autorizacion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="codigo_del_medicamento" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="tipo_de_medicamento" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="nombre_genérico_del_medicamento" Type="System.String" DbType="VarChar(250)" CanBeNull="true" />
      <Column Name="forma_farmacéutica" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="concentracion_del_medicamento" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="unidad_de_medida_del_medicamento" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="numero_de_unidades" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="valor_unitario_de_medicamento" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="valor_total_de_medicamento" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="prestador" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="descripcion_tipo_de_medicamento" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="ciudad_prestador" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="regional_prestador" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="posible_duplicado" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.rips_depurados_an_carguedtll" Member="rips_depurados_an_carguedtll">
    <Type Name="rips_depurados_an_carguedtll">
      <Column Name="id_cague_dtll" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_cargue_base" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="numero_de_la_factura" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="codigo_prestador_de_servicios_de_salud" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="tipo_identificacion_de_la_madre" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="numero_identificacion_de_la_madre" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="fecha_de_nacimiento_del_recien_nacido" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="hora_de_nacimiento" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="edad_gestacional" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="control_prenatal" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="sexo" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="peso" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="diagnostico_del_recien_nacido" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="causa_basica_de_muerte" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="fecha_de_muerte_del_recien_nacido" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="hora_de_muerte_del_recien_nacido" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="prestador" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="descripcion_control_prenatal" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="descripcion_diagnostico_del_recien_nacido" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="descripcion_causa_basica_de_muerte" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="grupo_dx" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="ciudad_prestador" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="regional_prestador" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="posible_duplicado" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.rips_depurados_ap_carguedtll" Member="rips_depurados_ap_carguedtll">
    <Type Name="rips_depurados_ap_carguedtll">
      <Column Name="id_cague_dtll" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_cargue_base" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="numero_factura" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="codigo_prestador_servicios_de_salud" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="tipo_identificacion_usuario" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="numero_identificacion_usuario" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="fecha_procedimiento" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="numero_autorizacion" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="codigo_procedimiento" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ambito_realizacion_procedimiento" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="finalidad_procedimiento" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="personal_que_atiende" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="diagnostico_principal" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="diagnostico_relacionado" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="complicacion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="forma_realizacion_acto_quirurgico" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="valor_del_procedimiento" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="prestador" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="descripcion_codigo_del_procedimiento" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="descripcion_ambito_de_realizacion_del_procedimiento" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="descripcion_finalidad_del_procedimiento" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="descripcion_personal_que_atiende" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="descripcion_forma_de_realizacion_del_acto_quirurgico" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="descripcion_diagnostico_principal" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="descripcion_diagnostico_relacionado" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="descripcion_complicacion" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="grupo_dx" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="ciudad_prestador" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="regional_prestador" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="posible_duplicado" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>