//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECOPETROL_COMMON.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=138.121.200.242\\MSSQLSERVER2012;Initial Catalog=medicamentos_pruebas;" +
            "User ID=adminsamirs2011;Connect Timeout=120")]
        public string medicamentos_pruebasConnectionString {
            get {
                return ((string)(this["medicamentos_pruebasConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=138.121.202.74;Initial Catalog=ecopetrol;Persist Security Info=True;U" +
            "ser ID=userappsami;Password=Srs_Asa*2023#;Connect Timeout=120")]
        public string ecopetrolConnectionString {
            get {
                return ((string)(this["ecopetrolConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=138.121.202.74;Initial Catalog=ecopetrol_pruebas;Persist Security Inf" +
            "o=True;User ID=userappsami;Password=Srs_Asa*2023#;Connect Timeout=120")]
        public string ecopetrol_pruebasConnectionString {
            get {
                return ((string)(this["ecopetrol_pruebasConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=138.121.200.242\\MSSQLSERVER2012;Initial Catalog=medicamentos;User ID=" +
            "userappsami;Password=Srs_Asa*2023#")]
        public string medicamentosConnectionString {
            get {
                return ((string)(this["medicamentosConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=138.121.200.242\\MSSQLSERVER2012;Initial Catalog=prestadores;User ID=u" +
            "serappsami")]
        public string prestadoresConnectionString {
            get {
                return ((string)(this["prestadoresConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=138.121.200.242;Initial Catalog=analitica_pruebas;Persist Security In" +
            "fo=True;User ID=userappsami")]
        public string analitica_pruebasConnectionString {
            get {
                return ((string)(this["analitica_pruebasConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=138.121.202.74;Initial Catalog=ecopetrol;Persist Security Info=True;U" +
            "ser ID=userappsami;Connect Timeout=120")]
        public string ecopetrolConnectionString2 {
            get {
                return ((string)(this["ecopetrolConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=138.121.202.74;Initial Catalog=ecopetrol_pruebas;Persist Security Inf" +
            "o=True;User ID=userappsami;Connect Timeout=120")]
        public string ecopetrol_pruebasConnectionString1 {
            get {
                return ((string)(this["ecopetrol_pruebasConnectionString1"]));
            }
        }
    }
}
