using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Reflection;
using System.Text.RegularExpressions;
using System.Web;

namespace AsaludEcopetrol.Exten
{
    public static class TableExtensions
    {
        public static void BulkInsert<TModelEntity>(this System.Data.Linq.Table<TModelEntity> table, IList<TModelEntity> entities)
          where TModelEntity : class
        {
            if ((entities == null) || (!entities.Any()))
            {
                return;
            }

            var modelEntityType = typeof(TModelEntity);

            // Retrieve a TableAttribute that is assigned to the class generated by LINQ to SQL (MSLinqToSQLGenerator)
            var tableAttribute =
                modelEntityType.GetCustomAttributes(typeof(System.Data.Linq.Mapping.TableAttribute), false)
                    .Cast<System.Data.Linq.Mapping.TableAttribute>()
                    .Single();

            // Retrieve all properties with ColumnAttribute
            var columnProperties =
                modelEntityType.GetProperties()
                    .Where(p => p.GetCustomAttributes(typeof(System.Data.Linq.Mapping.ColumnAttribute), false).Any());

            // Create a DataTable and initialize columns
            var dataTable = new DataTable(tableAttribute.Name);
            foreach (var columnProperty in columnProperties)
            {
                var type = columnProperty.PropertyType;

                if ((type.IsGenericType) && (type.GetGenericTypeDefinition() == typeof(Nullable<>)))
                {
                    var underlyingType = Nullable.GetUnderlyingType(columnProperty.PropertyType);

                    var column = new DataColumn(columnProperty.Name, underlyingType);

                    dataTable.Columns.Add(column);
                }
                else
                {
                    dataTable.Columns.Add(new DataColumn(columnProperty.Name, type));
                }
            }

            // Add data (rows) to the created DataTable
            foreach (var modelEntity in entities)
            {
                var values = columnProperties.Select(p => p.GetValue(modelEntity, null)).ToArray();

                dataTable.Rows.Add(values);
            }

            // Bulk insert data
            using (SqlConnection sqlConnection = new SqlConnection(table.Context.Connection.ConnectionString))
            {
                sqlConnection.Open();
                SqlBulkCopy sqlBulkCopy = new SqlBulkCopy(sqlConnection, SqlBulkCopyOptions.FireTriggers, null)
                {
                    DestinationTableName = tableAttribute.Name
                };

                try
                {
                    sqlBulkCopy.BulkCopyTimeout = 5000;
                    sqlBulkCopy.WriteToServer(dataTable);
                    sqlConnection.Close();

                }
                catch(Exception ex)
                {
                    var error = ex.Message;
                    if (ex.Message.Contains("Received an invalid column length from the bcp client for colid"))
                    {
                        string pattern = @"\d+";
                        Match match = Regex.Match(ex.Message.ToString(), pattern);
                        var index = Convert.ToInt32(match.Value) - 1;

                        FieldInfo fi = typeof(SqlBulkCopy).GetField("_sortedColumnMappings", BindingFlags.NonPublic | BindingFlags.Instance);
                        var sortedColumns = fi.GetValue(sqlBulkCopy);
                        var items = (Object[])sortedColumns.GetType().GetField("_items", BindingFlags.NonPublic | BindingFlags.Instance).GetValue(sortedColumns);

                        FieldInfo itemdata = items[index].GetType().GetField("_metadata", BindingFlags.NonPublic | BindingFlags.Instance);
                        var metadata = itemdata.GetValue(items[index]);

                        var column = metadata.GetType().GetField("column", BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance).GetValue(metadata);
                        var length = metadata.GetType().GetField("length", BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance).GetValue(metadata);
                    }
                }
            }
        }
    }
}